# --- LICA specific parameters ---

action_selector: "gumbel"
epsilon_start: .5
epsilon_finish: .01
epsilon_anneal_time: 100000
mask_before_softmax: True # set to True for entropy regularization

runner: "parallel"

buffer_size: 32
batch_size_run: 16
batch_size: 32

td_lambda: 0.8

# update the target network every {} training steps
target_update_interval: 200

# use tc
agent_output_type: "pi_logits"
learner: "tc_learner"
entropy_coef: 0.06 # 0.03 for 3s5z_vs_3s6z, 0.06 for all others
hiden_dim_rate: 4

n_layers: 3
n_heads: 4
d_ff: 256
d_k: 128
d_v: 128

name: "tc_without_layernorm"
